name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install texinfo
      run: sudo apt-get install texinfo
      
    - name: Run make gh-html
      run: make gh-html
